apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-postgres-config
  labels:
    app: {{ .Release.Name }}-postgres
data:
  POSTGRES_DB: {{ .Values.dbName }}
  POSTGRES_USER: {{ .Values.dbUser }}
  POSTGRES_PASSWORD: {{ .Values.dbPassword }}
